<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>bootstrap</AssemblyName>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.7.2" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="3.7.*" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.*" />
  </ItemGroup>
</Project>
